cabinetoffice/gap-find-web

- __tests__/components/homepage/heading-blurb.test.js
- __tests__/pages/home.test.js
- pages/index.js
- src/components/homepage/heading-blurb/HomePageHeadingBlurb.js
Removed references to pilot scheme and government grants community from home page.
> GAP-1806: Home page content changes

- .snyk
- middleware.ts
- src/utils/axios.ts
- src/utils/logger.ts
Restoring some work that was lost when editing the commit.
> omit cookie header from logs

- .github/workflows/pushImage.yml
> Adding env files to docker image build job

- src/components/grant-details-page/grant-details-sidebar/GrantDetailsSidebar.js
> removes next link to resolve client side error

- pages/newsletter/confirmation.tsx
> fixes request body issue

- pages/notifications/manage-notifications/index.tsx
> Adding logs for debugging manage notifications

- cypress/utils/checkSaveSearchData.js
- pages/index.js
- pages/notifications/manage-notifications/index.tsx
- src/utils/jwt.ts
> removing console logs

- .gitignore
- README.md
- __tests__/components/confirmation_message.test.js
- __tests__/pages/grant-pid-page.test.js
- __tests__/pages/notifications/manage-notifications.data.js
- __tests__/pages/notifications/manage-notifications.test.js
- middleware.ts
- package.json
- pages/api/newsletter/unsubscribe.test.ts
- pages/api/newsletter/unsubscribe.ts
- pages/login-notice/[type].tsx
- pages/newsletter/confirmation.tsx
- pages/newsletter/index.tsx
- pages/newsletter/unsubscribe/[slug].tsx
- pages/notifications/manage-notifications/index.tsx
- pages/unsubscribe/[id].tsx
- src/components/confirmation-message/ConfirmationMessage.js
- src/service/newsletter/newsletter-subscription-service.ts
- src/utils/constants.js
[GAP-1975](https://technologyprogramme.atlassian.net/browse/GAP-1975)
Get subscribe and unsubscribe journeys working for One Login, update readme and .gitignore
https://github.com/cabinetoffice/gap-find-backend/pull/65
[GAP-1975]: https://technologyprogramme.atlassian.net/browse/GAP-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-1975: Update 'Sign up for grant updates' Newsletter to use One Login

- __tests__/pages/notifications/manage-notifications.data.js
- __tests__/pages/notifications/manage-notifications.test.js
> GAP-1975|fix newsletter tests

- .snyk
- package.json
- src/utils/axios.ts
- yarn.lock
Upgrades axios to latest version
> Upgrades axios to 1.6.0

- __tests__/pages/notifications/manage-notifications.test.js
- pages/notifications/manage-notifications/index.tsx
- src/components/notification-banner/MigrationBanner.tsx
Related to GAP-2090,
This scenario should never actually happen, this is a 'just in case' guard.
> Hide migration banner when no migration type is passed from user-service

- __tests__/service/subscription_service.test.ts
- pages/api/newsletter/unsubscribe.test.ts
- pages/api/newsletter/unsubscribe.ts
- pages/unsubscribe/[id].tsx
- src/service/newsletter/newsletter-subscription-service.test.js
- src/service/newsletter/newsletter-subscription-service.ts
- src/service/subscription-service.ts
> Gap 2267: unsubscribe clean up

- __tests__/pages/api/notification-signup.test.js
- __tests__/pages/notifications/deleteSearch.test.js
- __tests__/pages/notifications/manage-notifications.data.js
- __tests__/pages/notifications/manage-notifications.test.js
- __tests__/pages/save-search/email.test.js
- __tests__/pages/save-search/notifications.test.js
- __tests__/service/subscription_service.test.ts
- middleware.ts
- pages/api/notification-signup/[token].js
- pages/login-notice/[type].tsx
- pages/notifications/delete-saved-search/[slug].js
- pages/notifications/manage-notifications/index.tsx
- pages/save-search/email.js
- pages/save-search/notifications.tsx
- pages/unsubscribe/[id].tsx
- src/service/saved_search_service.test.js
- src/service/saved_search_service.ts
- src/service/subscription-service.ts
- src/types/subscription.ts
- src/utils/constants.ts
- src/utils/index.ts
- src/utils/transform.js
Updates saved search to use One Login when `ONE_LOGIN_ENABLED == true`
[Related BE PR](https://github.com/cabinetoffice/gap-find-backend/pull/70)
[Ticket # and link](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-1976)
> update saved search to use one login

- __tests__/components/homepage/sidebar.test.js
- __tests__/middleware.test.ts
- __tests__/pages/home.test.js
- middleware.ts
- pages/api/newsletter-signup/[token].ts
- pages/login-notice/[type].tsx
- pages/newsletter/index.tsx
- pages/newsletter/unsubscribe/[slug].tsx
- pages/notifications/manage-notifications/index.tsx
- pages/save-search/notifications.tsx
- src/components/homepage/sidebar/HomepageSidebar.js
- src/components/notification-banner/MigrationBanner.tsx
- src/components/notification-banner/migrationContentMap.ts
- src/utils/index.ts
> fix import structure breaking site in dev mode

- src/components/partials/header/Header.tsx
> Hide auth navbar when OL not enabled

- __tests__/pages/notifications/unsubscribe.test.js
- pages/notifications/unsubscribe/[slug].js
- src/utils/contentFulPage.ts
fixes https://technologyprogramme.atlassian.net/browse/GAP-2283
> redirect user away when attempting to unsubscribe from null subscription

- middleware.ts
- src/components/newsletter/NewsletterCallToAction.tsx
https://technologyprogramme.atlassian.net/browse/GAP-2284
> newsletter goes through login notice

- pages/newsletter/unsubscribe/[slug].tsx
- pages/notifications/delete-saved-search/[slug].js
- pages/notifications/unsubscribe/[slug].js
> Remove breadcrumbs on notification unsub journeys

- pages/notifications/manage-notifications/index.tsx
Fixes https://technologyprogramme.atlassian.net/browse/GAP-2288
Counts migration status of `NEW_USER` as a successful migration for the purposes of content displayed to user.
> count migration status NEW_USER as successful migration

- pages/login-notice/[type].tsx
> change find login button text to Continue to GOV.UK One Login

- src/components/partials/header/Header.tsx
> replace sign out link with anchor tag

- __tests__/components/grant-details/grant-details-apply-button.test.js
- pages/login-notice/[type].tsx
- src/components/grant-details-page/grant-details-apply-button/GrantDetailsApplyButton.js
- src/components/partials/header/Header.tsx
> Merging develop into release branch

- src/components/partials/header/Header.tsx
- styles/globals.scss
https://technologyprogramme.atlassian.net/browse/GAP-2383
As part of code improvements, it was recommended to use <Link> instead of <a> for navigation to `api/logout` - however, this change means the button doesn't benefit from all the CSS rules designed for <a> elements. Have reverted the change for now.
> GAP-2383: Sign out button position

- pages/api/logout.ts
Fix for https://technologyprogramme.atlassian.net/browse/GAP-2382
> rename logout api file

- pages/apply/[pid].js
Changes the redirect to be a more pleasant experience for previously un-auth'd users
[GAP-2360]( https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2096)
[GAP-2360]: https://technologyprogramme.atlassian.net/browse/GAP-2360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP:2360 Change redirect for un-auth'd users

- pages/index.js
[GAP-2402](https://technologyprogramme.atlassian.net/browse/GAP-2402)
trust
[GAP-2402]: https://technologyprogramme.atlassian.net/browse/GAP-2402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GAP-2402 | verify thomas as google site owner

- __tests__/pages/apply/[pid].test.js
- __tests__/pages/grant-pid-page.test.js
- __tests__/pages/subscriptions/signup.test.js
- pages/apply/[pid].js
- pages/grants/[pid].js
- pages/subscriptions/signup.js
- src/utils/contentFulPage.ts
- src/utils/grantDetails.js
> fix /apply/[pid]

- .github/workflows/promoteToProd.yml
- .github/workflows/pushImage.yml
> Tmi2 531/run as aws role

- pages/apply/[pid].js
> fix redirect url

- Dockerfile
> format logs as json when deployed

- pages/notifications/delete-saved-search/[slug].js
- pages/notifications/unsubscribe/[slug].js
GAP-2431: https://technologyprogramme.atlassian.net/browse/GAP-2413
> GAP-2431: Cancel button for saved search deletion not consistent

- Dockerfile
- package.json
> fix logging

- __tests__/middleware.test.ts
- middleware.ts
- src/utils/jwt.ts
> fix middleware cookie parsing

- src/components/partials/header/Header.tsx
> fix sign out link

- __tests__/components/grant-details/grant-details-header.test.js
- __tests__/components/searchpage/search-result-card.test.js
- __tests__/utils/adjustDateTimes.test.js
- src/components/grant-details-page/grant-details-header/GrantDetailsHeader.js
- src/components/search-page/search-result-card/SearchResultCard.js
- src/utils/adjustDateTimes.js
Hotfix release 7.1
https://technologyprogramme.atlassian.net/browse/TMI2-703
> HOTFIX Release 7.1

- __tests__/pages/unsubscribe/[id].test.js
- pages/unsubscribe/[id].tsx
[TMI2-724 - Remove support email content from unsubscribe confirmation page](https://technologyprogramme.atlassian.net/browse/TMI2-724)
> TMI2-724 - Removed support email content from unsubscribe confirmation page

- __tests__/pages/apply/[pid].test.js
- pages/apply/[pid].js
> assume v1 external grant if no db entry

- .env.example
- __tests__/components/homepage/sidebar.test.js
- pages/_app.js
- src/components/homepage/sidebar/HomepageSidebar.js
- src/service/user-service.ts
Ticket # and link[ GAP-2490](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2490)
Adds logic using the user roles to decide where href on home page should direct a user
> GAP-2490: Bypass oneLogin for a logged in user

- pages/index.js
> GAP-2563: Handover Google Search Console

- .eslintrc.js
- __tests__/pages/unsubscribe/[id].test.js
- pages/api/user/delete.test.js
- pages/api/user/delete.ts
- pages/api/user/migrate.test.js
- pages/api/user/migrate.ts
- pages/unsubscribe/[id].tsx
- src/utils/axios.ts
- src/utils/logger.ts
> remove console logs

- package.json
- yarn.lock
> GAP-2520 | remove husky upgrade to fix build

- .github/workflows/pushImage.yml
> actions checkout version to v4
